import os
from dotenv import load_dotenv

load_dotenv()

BOT_TOKEN = os.getenv("BOT_TOKEN")

_admin_id = os.getenv("ADMIN_ID")
ADMIN_ID = int(_admin_id) if _admin_id else None

DATABASE_URL = os.getenv("DATABASE_URL")

CARD_NUMBER = os.getenv("CARD_NUMBER", "")
CARD_OWNER = os.getenv("CARD_OWNER", "")

MIN_PAYMENT = 5000

LIKE_LIMIT_FREE = 5
LIKE_LIMIT_PREMIUM = 20

PRICE_CARD_SIMPLE = 5000
PRICE_CARD_SERIOUS = 15000
PRICE_CARD_FAMILY = 40000
PRICE_LOCATION = 25000
PRICE_HIDDEN = 10000
PRICE_PREMIUM = 50000
PRICE_PREMIUM_VIP = 100000

STORY_DURATION_FREE = 24
STORY_DURATION_VIP = 48
